#!/bin/sh
# This file is licensed under the BSD-3-Clause license.
# See the AUTHORS and LICENSE files for more information.
#
# echo an HTML fragment in the middle of predefined HTML
# also sets HTML title

PAGE_FRAGMENT="$1"
TITLE="$2"

[ -z "${PAGE_FRAGMENT}" ] && printf '%s\n' 'Must provide file' && exit 1
[ -z "${TITLE}" ] && printf '%s\n' 'Must provide title' && exit 1

# header/aside
printf "<!DOCTYPE html>
<html lang='en'>
<head>
  <title>%s</title>
  <meta charset='utf-8'>

  <link rel='stylesheet' type='text/css' href='/css/style.css' />
</head>
<body>
<div id='aside'>
  <h1><a href='/'>zfsnap</a></h1>
  <ul id='nav'>
    <li><a href='about.html'>about</a></li>
    <li><a href='docs.html'>documentation</a></li>
    <li><a href='access.html'>get zfsnap</a></li>
    <li><a href='contribute.html'>contribute</a></li>
    <li><a href='https://raw.githubusercontent.com/zfsnap/zfsnap/master/NEWS'>news</a></li>
  </ul>
</div><!-- close #aside -->\n" "${TITLE}"

# main
printf "<div id='main'>\n"
cat < "$PAGE_FRAGMENT"
printf "</div><!-- close #main -->\n"

# footer
printf "
<div id='footer'>
  <p>This website's code is <a href='https://github.com/zfsnap/zfsnap.github.io'>
     hosted on GitHub</a>.<br />
     Patches and suggestions are welcome.</p>
</div><!-- close #footer -->
</body>
</html>\n"

